apiVersion: v1
kind: ConfigMap
metadata:
  name: node
  namespace: simulation
data:
  node.json: |
    {
      "simulation name": "sphere",
      "mongodb": {
        "url": "mongodb://simulation:Passw0rd@mongodb.simulation.svc.cluster.local:27017/",
        "database": "simulation",
        "collection": "logs"
      },
      "seed": {
        "url": "ws://seed.simulation.svc.cluster.local:8080/simulation"
      },
      "logs": [
        "current position",
        "links",
        "routing 1d required",
        "routing 2d required",
        "link status"
      ]
    }
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: node
  namespace: simulation
spec:
  serviceName: node
  replicas: 24
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
      - name: node
        image: llamerada/colonio-sim-node:dev
        command: ["/simulations"]
        args: ["-m", "-p", "12", "/etc/node/node.json"]
        volumeMounts:
        - name: config-volume
          mountPath: /etc/node
      terminationGracePeriodSeconds: 0
      volumes:
      - name: config-volume
        configMap:
          name: node
---
apiVersion: v1
kind: Service
metadata:
  name: node
  labels:
    app: node
spec:
  clusterIP: None
  selector:
    app: node
